<?php

namespace AppBundle\Repository;

/**
 * PostBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostBackRepository extends \Doctrine\ORM\EntityRepository
{
}
